### ISSUE TITLE
Add pop-out effects

### ISSUE THREAD

**Issue by ghost** [IanLunn/Hover#45]
Hey! I created a flat shadow pop out effect that I think would be a nice addition to your library. You can check out my code here :http://jsfiddle.net/Lumz96ex/5/ . I'm new to Github and decided to explore CSS related repositories since CSS and HTML are my strong suit. Let me know what you think.

**Comment by IanLunn** [comment]
Hi. Nice code, we haven't used `box-shadow` transitions in the way you have as yet so that could extend the possibilities. I think the effect you've linked to is a little too specific and couldn't easily be added to multiple websites but you're on the right track. Would be happy to add similar effects that are more subtle.

**Comment by DannyDepp** [comment]
So I took into consideration as to what you said and fixed up the code a bit to give it that subtlety that the
rest of your library has. http://jsfiddle.net/Lumz96ex/6/. Thanks for considering my idea!
