### ISSUE TITLE
How animate on click

### ISSUE THREAD

**Issue by cubiczx** [IanLunn/Hover#92]
How animate on click?

**Comment by PandaWood** [comment]
I asked this question myself. 
For my situation, I was able to set my div to the the hover css class (eg pop) and because it implements the :active and :focus selectors, mousedown caused these to fire as well.
So that kind of worked on click... only problem is it only animates as long as you have the mouse down (in my case) - I guess it's only "active" while the mouse is down.
So that's not a great solution, though worked well for me

I'd like to hear any other ideas about how to do this - how to cause the same animation as hover, but via mouse click (perhaps some javascript would be needed)...

**Comment by IanLunn** [comment]
See duplicate https://github.com/IanLunn/Hover/issues/63
