### ISSUE TITLE
Float shadow looped animation bug

### ISSUE THREAD

**Issue by arapoport** [IanLunn/Hover#98]
If cursor is just on the edge of the element then element will float away and this will cause the backwards movement which will bring the element back under the cursor and that will cause another loop :-)

See this GIF:

![shadow_animation_bug](https://cloud.githubusercontent.com/assets/3393725/17326783/deffc90e-58b3-11e6-9d1d-e84c340e92f3.gif)

**Comment by jeffrey008** [comment]
I think that is a default behaviour because 
1. The div moves up
2. The div is not in hover state anymore
3. The div returns to normal state
4. The div is hovered by mouse
5. Go back to 1.

Anyway I think this bug is not common because you need to move cursor to a really precise position to produce this bug.

**Comment by IanLunn** [comment]
Yes, I wouldn't really call it a bug. We might be able to work around it by placing a pseudo-element where the element started so the hover event is still captured but a lot of effects already use pseudo-elements so this might not be an option and will lead to bloat. I am tempted to leave the issue be unless someone has a better solution.

**Comment by IanLunn** [comment]
Closing as this isn't a bug. Would be nice to get a solution if anyone has suggestions.
