### ISSUE TITLE
Curious about something

### ISSUE THREAD

**Issue by batusai513** [IanLunn/Hover#99]
Hi, this is not really an issue, is just curiosity about the background transitions, i was wondering why the before pseudo element is visible if you are using a negative z-index, i see that you are using a transformZ, but i want to know the why of this behavior, if you also have articles or something where i can go deep on this it would be awesome.

thanks

**Comment by IanLunn** [comment]
It is due to stacking context. A couple of good articles:

- https://philipwalton.com/articles/what-no-one-told-you-about-z-index/
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

The `transformZ` is for the purpose of hardware acceleration.
